services:
  docs:
    image: squidfunk/mkdocs-material:latest
    container_name: docs
    restart: unless-stopped
    volumes:
      - ../../:/docs:ro
    command: serve --dev-addr=0.0.0.0:8000
    networks:
      - proxy
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.ragnalab.xyz`)"
      - "traefik.http.routers.docs.entrypoints=websecure"
      - "traefik.http.routers.docs.tls.certresolver=letsencrypt"
      - "traefik.http.services.docs.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"

      # Homepage
      - "homepage.group=Infrastructure"
      - "homepage.name=Documentation"
      - "homepage.icon=material-design-icons"
      - "homepage.href=https://docs.ragnalab.xyz"
      - "homepage.description=RagnaLab docs"

networks:
  proxy:
    external: true
