# Bookmarks Configuration
# https://gethomepage.dev/configs/bookmarks/

- Management:
    - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com

    - Tailscale:
        - icon: tailscale.png
          href: https://login.tailscale.com/admin/machines

    - GitHub:
        - icon: github.png
          href: https://github.com
