# Authelia Users Database

users:
  rushil:
    disabled: false
    displayname: 'Rushil'
    email: 'rushil@ragnalab.xyz'
    groups:
      - admin
      - powerusers
      - family
    password: '$argon2id$v=19$m=256,t=1,p=2$lnSkWpCaAWaCqPMEVEECRw$dYqQNq4YGNbJQpPjYRZXUi72i915yE2R/jQjtHSvJSo'
